# Assignment 6

# Text Summarisation

# Text 1

#### Setting up a text summarization using NLTK and NetworkX

In [1]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx


#### Processing a paragraph from a text file into individual sentences and then further split them into words

In [2]:
file = open(r"C:\Users\ruchitha\OneDrive\Documents\text 1.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))


Nach der Schule gehe ich oft mit meinen Freundinnen im Park spazieren, manchmal essen wir ein Eis
Am Samstag gehen wir oft ins Kino
Am Sonntag schlafe ich lange, dann koche ich mit meiner Mutter das Mittagessen
Nach dem Essen gehen wir mit dem Hund am See spazieren
Sonntag ist mein Lieblingstag!


#### Print out the sentences after splitting them into words

In [3]:
print("Sentences are ", sentences)


Sentences are  [['Nach', 'der', 'Schule', 'gehe', 'ich', 'oft', 'mit', 'meinen', 'Freundinnen', 'im', 'Park', 'spazieren,', 'manchmal', 'essen', 'wir', 'ein', 'Eis'], ['Am', 'Samstag', 'gehen', 'wir', 'oft', 'ins', 'Kino'], ['Am', 'Sonntag', 'schlafe', 'ich', 'lange,', 'dann', 'koche', 'ich', 'mit', 'meiner', 'Mutter', 'das', 'Mittagessen'], ['Nach', 'dem', 'Essen', 'gehen', 'wir', 'mit', 'dem', 'Hund', 'am', 'See', 'spazieren'], ['Sonntag', 'ist', 'mein', 'Lieblingstag!']]


#### Function helps to compute the similarity between two sentences

In [4]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)


#### Calculates the similarity between each pair of sentences using the sentence_similarity function and fills in the similarity matrix

In [5]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.1833397  0.18786729 0.26906912 0.        ]
 [0.1833397  0.         0.09759001 0.31448545 0.        ]
 [0.18786729 0.09759001 0.         0.14322297 0.12909944]
 [0.26906912 0.31448545 0.14322297 0.         0.        ]
 [0.         0.         0.12909944 0.         0.        ]]


#### Provides with PageRank scores for each sentence, indicating their relative importance within the text

In [6]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)


scores {0: 0.23102714154777504, 1: 0.21414431407288662, 2: 0.22343931492891606, 3: 0.25743135420660895, 4: 0.07395787524381325}


#### Provides with a ranked list of sentences based on their importance within the text

In [7]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.25743135420660895, ['Nach', 'dem', 'Essen', 'gehen', 'wir', 'mit', 'dem', 'Hund', 'am', 'See', 'spazieren']), (0.23102714154777504, ['Nach', 'der', 'Schule', 'gehe', 'ich', 'oft', 'mit', 'meinen', 'Freundinnen', 'im', 'Park', 'spazieren,', 'manchmal', 'essen', 'wir', 'ein', 'Eis']), (0.22343931492891606, ['Am', 'Sonntag', 'schlafe', 'ich', 'lange,', 'dann', 'koche', 'ich', 'mit', 'meiner', 'Mutter', 'das', 'Mittagessen']), (0.21414431407288662, ['Am', 'Samstag', 'gehen', 'wir', 'oft', 'ins', 'Kino']), (0.07395787524381325, ['Sonntag', 'ist', 'mein', 'Lieblingstag!'])]


#### Generates a summary by selecting the top n sentences with the highest PageRank scores

In [8]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=4
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))


How many sentences do you want in the summary? 3


#### Displays the summary, constructed from the top-ranked sentences

In [9]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))


Summarize Text: 
 Nach dem Essen gehen wir mit dem Hund am See spazieren. Nach der Schule gehe ich oft mit meinen Freundinnen im Park spazieren, manchmal essen wir ein Eis. Am Sonntag schlafe ich lange, dann koche ich mit meiner Mutter das Mittagessen


# Text 2

#### Processing a paragraph from a text file into individual sentences and then further split them into words

In [10]:
file = open(r"C:\Users\ruchitha\OneDrive\Documents\text 2.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Pierre est un jeune garçon de 14 ans
Il vit à Paris avec ses parents et sa petite sœur Julie, âgée de 8 ans
Toute la petite famille habite dans un grand appartement au 3ème étage d'un immeuble situé près de la Tour Eiffel
Ainsi, Pierre a le privilège d'admirer chaque jour l'un des monuments les plus visités au monde !.Pour se rendre au collège, Pierre prend le métro à la station Ecole Militaire et sort au collège Claude Debussy
Le trajet ne dure que 20 minutes ! Le week-end, Pierre aime passer du temps en famille
Tous les quatre en profitent pour visiter les musées parisiens, aller au cinéma, faire du shopping, ou se balader dans l'un des nombreux parcs de la capitale.


#### Print out the sentences after splitting them into words

In [11]:
print("Sentences are ", sentences)

Sentences are  [['Pierre', 'est', 'un', 'jeune', 'garçon', 'de', '14', 'ans'], ['Il', 'vit', 'Ã\xa0', 'Paris', 'avec', 'ses', 'parents', 'et', 'sa', 'petite', 'sÅ“ur', 'Julie,', 'âgée', 'de', '8', 'ans'], ['Toute', 'la', 'petite', 'famille', 'habite', 'dans', 'un', 'grand', 'appartement', 'au', '3ème', 'étage', "d'un", 'immeuble', 'situé', 'près', 'de', 'la', 'Tour', 'Eiffel'], ['Ainsi,', 'Pierre', 'a', 'le', 'privilège', "d'admirer", 'chaque', 'jour', "l'un", 'des', 'monuments', 'les', 'plus', 'visités', 'au', 'monde', '!.Pour', 'se', 'rendre', 'au', 'collège,', 'Pierre', 'prend', 'le', 'métro', 'Ã\xa0', 'la', 'station', 'Ecole', 'Militaire', 'et', 'sort', 'au', 'collège', 'Claude', 'Debussy'], ['Le', 'trajet', 'ne', 'dure', 'que', '20', 'minutes', '!', 'Le', 'week-end,', 'Pierre', 'aime', 'passer', 'du', 'temps', 'en', 'famille'], ['Tous', 'les', 'quatre', 'en', 'profitent', 'pour', 'visiter', 'les', 'musées', 'parisiens,', 'aller', 'au', 'cinéma,', 'faire', 'du', 'shop

#### Function helps to compute the similarity between two sentences

In [12]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

#### Calculates the similarity between each pair of sentences using the sentence_similarity function and fills in the similarity matrix

In [13]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.1767767  0.15075567 0.10425721 0.08111071 0.06565322]
 [0.1767767  0.         0.10660036 0.07372098 0.         0.04642383]
 [0.15075567 0.10660036 0.         0.15717365 0.0489116  0.1979519 ]
 [0.10425721 0.07372098 0.15717365 0.         0.20295303 0.24641356]
 [0.08111071 0.         0.0489116  0.20295303 0.         0.08520286]
 [0.06565322 0.04642383 0.1979519  0.24641356 0.08520286 0.        ]]


#### Provides with PageRank scores for each sentence, indicating their relative importance within the text

In [14]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)


scores {0: 0.16768590609090062, 1: 0.12259565995486688, 2: 0.18649891276878533, 3: 0.2178393851371543, 4: 0.12496980583094575, 5: 0.18041033021734693}


#### Provides with a ranked list of sentences based on their importance within the text

In [15]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.2178393851371543, ['Ainsi,', 'Pierre', 'a', 'le', 'privilège', "d'admirer", 'chaque', 'jour', "l'un", 'des', 'monuments', 'les', 'plus', 'visités', 'au', 'monde', '!.Pour', 'se', 'rendre', 'au', 'collège,', 'Pierre', 'prend', 'le', 'métro', 'Ã\xa0', 'la', 'station', 'Ecole', 'Militaire', 'et', 'sort', 'au', 'collège', 'Claude', 'Debussy']), (0.18649891276878533, ['Toute', 'la', 'petite', 'famille', 'habite', 'dans', 'un', 'grand', 'appartement', 'au', '3ème', 'étage', "d'un", 'immeuble', 'situé', 'près', 'de', 'la', 'Tour', 'Eiffel']), (0.18041033021734693, ['Tous', 'les', 'quatre', 'en', 'profitent', 'pour', 'visiter', 'les', 'musées', 'parisiens,', 'aller', 'au', 'cinéma,', 'faire', 'du', 'shopping,', 'ou', 'se', 'balader', 'dans', "l'un", 'des', 'nombreux', 'parcs', 'de', 'la', 'capitale.']), (0.16768590609090062, ['Pierre', 'est', 'un', 'jeune', 'garçon', 'de', '14', 'ans']), (0.12496980583094575, ['Le', 'trajet', 'ne', 'd

#### Generates a summary by selecting the top n sentences with the highest PageRank scores

In [16]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=5
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))


How many sentences do you want in the summary? 5


#### Displays the summary, constructed from the top-ranked sentences

In [17]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))


Summarize Text: 
 Ainsi, Pierre a le privilège d'admirer chaque jour l'un des monuments les plus visités au monde !.Pour se rendre au collège, Pierre prend le métro à la station Ecole Militaire et sort au collège Claude Debussy. Toute la petite famille habite dans un grand appartement au 3ème étage d'un immeuble situé près de la Tour Eiffel. Tous les quatre en profitent pour visiter les musées parisiens, aller au cinéma, faire du shopping, ou se balader dans l'un des nombreux parcs de la capitale.. Pierre est un jeune garçon de 14 ans. Le trajet ne dure que 20 minutes ! Le week-end, Pierre aime passer du temps en famille


# Text 3

#### Processing a paragraph from a text file into individual sentences and then further split them into words

In [18]:
file = open(r"C:\Users\ruchitha\OneDrive\Documents\text 3.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Mi abuelo Tomás.Mi abuelo Tomás tiene ochenta años y vive con nosotros
Tiene buena salud, aunque a veces dice que le duele una pierna, pero camina ágilmente cuando le llaman sus amigos para jugar a las cartas después de comer.Todos los domingos me lleva a ver el futbol y después me compra un helado.En vacaciones siempre viene con nosotros y le gusta mucho ir a la playa
A veces discute con mi padre cuando quiere ir a la montaña
Al final siempre se sale con la suya y mi padre acaba cediendo
Para compensarle siempre nos invita el primer día de vacaciones a un buen restaurante.Quiero mucho a mi abuelo.


#### Print out the sentences after splitting them into words

In [19]:
print("Sentences are ", sentences)

Sentences are  [['Mi', 'abuelo', 'Tomás.Mi', 'abuelo', 'Tomás', 'tiene', 'ochenta', 'años', 'y', 'vive', 'con', 'nosotros'], ['Tiene', 'buena', 'salud,', 'aunque', 'a', 'veces', 'dice', 'que', 'le', 'duele', 'una', 'pierna,', 'pero', 'camina', 'ágilmente', 'cuando', 'le', 'llaman', 'sus', 'amigos', 'para', 'jugar', 'a', 'las', 'cartas', 'después', 'de', 'comer.Todos', 'los', 'domingos', 'me', 'lleva', 'a', 'ver', 'el', 'futbol', 'y', 'después', 'me', 'compra', 'un', 'helado.En', 'vacaciones', 'siempre', 'viene', 'con', 'nosotros', 'y', 'le', 'gusta', 'mucho', 'ir', 'a', 'la', 'playa'], ['A', 'veces', 'discute', 'con', 'mi', 'padre', 'cuando', 'quiere', 'ir', 'a', 'la', 'montaña'], ['Al', 'final', 'siempre', 'se', 'sale', 'con', 'la', 'suya', 'y', 'mi', 'padre', 'acaba', 'cediendo'], ['Para', 'compensarle', 'siempre', 'nos', 'invita', 'el', 'primer', 'dÃ\xada', 'de', 'vacaciones', 'a', 'un', 'buen', 'restaurante.Quiero', 'mucho', 'a', 'mi', 'abuelo.']]


#### Function helps to compute the similarity between two sentences

In [20]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

#### Calculates the similarity between each pair of sentences using the sentence_similarity function and fills in the similarity matrix

In [21]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.15034619 0.14285714 0.22237479 0.05976143]
 [0.15034619 0.         0.39090011 0.15602162 0.37736595]
 [0.14285714 0.39090011 0.         0.29649973 0.29880715]
 [0.22237479 0.15602162 0.29649973 0.         0.12403473]
 [0.05976143 0.37736595 0.29880715 0.12403473 0.        ]]


#### Provides with PageRank scores for each sentence, indicating their relative importance within the text

In [22]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.13960409985527306, 1: 0.23626328715591705, 2: 0.24745969139965174, 3: 0.18389283385742253, 4: 0.19278008773173516}


#### Provides with a ranked list of sentences based on their importance within the text

In [23]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.24745969139965174, ['A', 'veces', 'discute', 'con', 'mi', 'padre', 'cuando', 'quiere', 'ir', 'a', 'la', 'montaña']), (0.23626328715591705, ['Tiene', 'buena', 'salud,', 'aunque', 'a', 'veces', 'dice', 'que', 'le', 'duele', 'una', 'pierna,', 'pero', 'camina', 'ágilmente', 'cuando', 'le', 'llaman', 'sus', 'amigos', 'para', 'jugar', 'a', 'las', 'cartas', 'después', 'de', 'comer.Todos', 'los', 'domingos', 'me', 'lleva', 'a', 'ver', 'el', 'futbol', 'y', 'después', 'me', 'compra', 'un', 'helado.En', 'vacaciones', 'siempre', 'viene', 'con', 'nosotros', 'y', 'le', 'gusta', 'mucho', 'ir', 'a', 'la', 'playa']), (0.19278008773173516, ['Para', 'compensarle', 'siempre', 'nos', 'invita', 'el', 'primer', 'dÃ\xada', 'de', 'vacaciones', 'a', 'un', 'buen', 'restaurante.Quiero', 'mucho', 'a', 'mi', 'abuelo.']), (0.18389283385742253, ['Al', 'final', 'siempre', 'se', 'sale', 'con', 'la', 'suya', 'y', 'mi', 'padre', 'acaba', 'cediendo']), (0.139604099855273

#### Generates a summary by selecting the top n sentences with the highest PageRank scores

In [24]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=3
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 2


#### Displays the summary, constructed from the top-ranked sentences

In [25]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))


Summarize Text: 
 A veces discute con mi padre cuando quiere ir a la montaña. Tiene buena salud, aunque a veces dice que le duele una pierna, pero camina ágilmente cuando le llaman sus amigos para jugar a las cartas después de comer.Todos los domingos me lleva a ver el futbol y después me compra un helado.En vacaciones siempre viene con nosotros y le gusta mucho ir a la playa
